# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_manager', '0002_auto_20160903_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='started_working',
            field=models.DateField(verbose_name='Date of Hire'),
        ),
    ]
